# Generated by Django 3.2.25 on 2025-05-09 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20250509_0050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductSize',
        ),
    ]
